---
- name: "Configure Hostname and DNS"
  hosts: arista_ceos
  tasks:
    - name: "Configure Basic Configuration on Arista Fabric"
      arista.eos.eos_config:
        authorize: yes
        lines:
          - "ip name-server {{ item }}"    
      loop: "{{ global['dns'] }}"
